pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode = RepositoriesMode.PREFER_SETTINGS
    repositories {
        mavenLocal()
        maven { url = 'https://maven.minecraftforge.net' }
        maven { url = 'https://libraries.minecraft.net' }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'mcp-reborn'

include ':mcp'
project(":mcp").projectDir = file("projects/mcp")

include ':addons:lwjgl-stubs'
include ':addons:jdk-stubs'
include ':addons:teavm-runtime'
include ':addons:web'
