plugins {
    id 'java'
}

group = 'top.steve3184.webmc'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.teavm:teavm-jso:0.13.1'
    implementation 'org.teavm:teavm-jso-apis:0.13.1'
    implementation project(':mcp')
}

compileJava {
    sourceCompatibility = '21'
    targetCompatibility = '21'
    options.compilerArgs = [
        '--patch-module', "java.base=$rootDir/../addons/jdk-stubs/locks",
        '--patch-module', "jdk.unsupported=$rootDir/../addons/jdk-stubs/sun-misc",
        '--patch-module', "java.base=$rootDir/../addons/jdk-stubs/jdk-extra",
    ]
}
