package org.apache.logging.log4j;
public interface Logger {
    String getName();
    void info(MarkerManager.Marker marker, CharSequence message);
    void info(CharSequence message);
    void info(MarkerManager.Marker marker, Object message);
    void info(Object message);
    void info(MarkerManager.Marker marker, CharSequence message, Throwable t);
    void info(CharSequence message, Throwable t);
    void info(MarkerManager.Marker marker, Object message, Throwable t);
    void info(Object message, Throwable t);
    void warn(MarkerManager.Marker marker, CharSequence message);
    void warn(CharSequence message);
    void warn(MarkerManager.Marker marker, Object message);
    void warn(Object message);
    void warn(MarkerManager.Marker marker, CharSequence message, Throwable t);
    void warn(CharSequence message, Throwable t);
    void warn(MarkerManager.Marker marker, Object message, Throwable t);
    void warn(Object message, Throwable t);
    void error(MarkerManager.Marker marker, CharSequence message);
    void error(CharSequence message);
    void error(MarkerManager.Marker marker, Object message);
    void error(Object message);
    void error(MarkerManager.Marker marker, CharSequence message, Throwable t);
    void error(CharSequence message, Throwable t);
    void error(MarkerManager.Marker marker, Object message, Throwable t);
    void error(Object message, Throwable t);
    void debug(MarkerManager.Marker marker, CharSequence message);
    void debug(CharSequence message);
    void debug(MarkerManager.Marker marker, Object message);
    void debug(Object message);
    void debug(MarkerManager.Marker marker, CharSequence message, Throwable t);
    void debug(CharSequence message, Throwable t);
    void debug(MarkerManager.Marker marker, Object message, Throwable t);
    void debug(Object message, Throwable t);
    void trace(MarkerManager.Marker marker, CharSequence message);
    void trace(CharSequence message);
    void trace(MarkerManager.Marker marker, Object message);
    void trace(Object message);
    void trace(MarkerManager.Marker marker, CharSequence message, Throwable t);
    void trace(CharSequence message, Throwable t);
    void trace(MarkerManager.Marker marker, Object message, Throwable t);
    void trace(Object message, Throwable t);
    boolean isInfoEnabled();
    boolean isWarnEnabled();
    boolean isErrorEnabled();
    boolean isDebugEnabled();
    boolean isTraceEnabled();
    boolean isInfoEnabled(MarkerManager.Marker marker);
    boolean isWarnEnabled(MarkerManager.Marker marker);
    boolean isErrorEnabled(MarkerManager.Marker marker);
    boolean isDebugEnabled(MarkerManager.Marker marker);
    boolean isTraceEnabled(MarkerManager.Marker marker);
}
