// chunks/loader.js - Dynamic chunk loader for WebMC
// Loads game.js chunks on demand

(function() {
    'use strict';

    const CHUNKS_DIR = 'chunks/';
    const loadedChunks = new Map();
    const loadingChunks = new Map();
    const pendingCallbacks = new Map();

    // Chunk manifest - generated by split script
    const MANIFEST = {
        total: 29,
        chunks: []
    };

    // Generate manifest from actual chunks
    (function buildManifest() {
        for (let i = 0; i < 29; i++) {
            MANIFEST.chunks.push({
                id: i,
                name: `chunk-${String(i).padStart(3, '0')}.js`,
                loaded: false
            });
        }
    })();

    window.__webmcChunks = {
        manifest: MANIFEST,
        loaded: loadedChunks,

        // Load a single chunk
        load: function(chunkId, callback) {
            chunkId = parseInt(chunkId);

            // Already loaded
            if (loadedChunks.has(chunkId)) {
                if (callback) callback(null, loadedChunks.get(chunkId));
                return Promise.resolve(loadedChunks.get(chunkId));
            }

            // Currently loading
            if (loadingChunks.has(chunkId)) {
                if (callback) {
                    const pending = pendingCallbacks.get(chunkId) || [];
                    pending.push(callback);
                    pendingCallbacks.set(chunkId, pending);
                }
                return loadingChunks.get(chunkId);
            }

            // Start loading
            const chunkName = `chunk-${String(chunkId).padStart(3, '0')}.js`;
            console.log('[mc-web/chunks] Loading chunk', chunkId, ':', chunkName);

            const loadPromise = new Promise((resolve, reject) => {
                const script = document.createElement('script');
                script.src = CHUNKS_DIR + chunkName;
                script.async = true;

                script.onload = function() {
                    console.log('[mc-web/chunks] Loaded chunk', chunkId);
                    loadedChunks.set(chunkId, true);
                    MANIFEST.chunks[chunkId].loaded = true;
                    loadingChunks.delete(chunkId);

                    // Call pending callbacks
                    const pending = pendingCallbacks.get(chunkId) || [];
                    pending.forEach(cb => cb(null, true));
                    pendingCallbacks.delete(chunkId);

                    resolve(true);
                };

                script.onerror = function(e) {
                    console.error('[mc-web/chunks] Failed to load chunk', chunkId, e);
                    loadingChunks.delete(chunkId);

                    const pending = pendingCallbacks.get(chunkId) || [];
                    pending.forEach(cb => cb(new Error('Failed to load chunk')));
                    pendingCallbacks.delete(chunkId);

                    reject(new Error('Failed to load chunk ' + chunkId));
                };

                document.head.appendChild(script);
            });

            loadingChunks.set(chunkId, loadPromise);

            if (callback) {
                pendingCallbacks.set(chunkId, [callback]);
            }

            return loadPromise;
        },

        // Preload chunks in background
        preload: function(startId, count) {
            console.log('[mc-web/chunks] Preloading chunks', startId, 'to', startId + count - 1);
            const promises = [];
            for (let i = startId; i < startId + count && i < MANIFEST.total; i++) {
                if (!loadedChunks.has(i)) {
                    promises.push(this.load(i));
                }
            }
            return Promise.all(promises);
        },

        // Load all chunks
        loadAll: function(onProgress) {
            console.log('[mc-web/chunks] Loading all chunks...');
            const promises = [];
            for (let i = 0; i < MANIFEST.total; i++) {
                promises.push(
                    this.load(i).then(() => {
                        if (onProgress) {
                            onProgress(i + 1, MANIFEST.total);
                        }
                    }).catch(e => {
                        console.error('[mc-web/chunks] Error loading chunk', i, e);
                    })
                );
            }
            return Promise.all(promises);
        },

        // Get load status
        getStatus: function() {
            return {
                loaded: loadedChunks.size,
                total: MANIFEST.total,
                loading: loadingChunks.size,
                percent: Math.round(loadedChunks.size / MANIFEST.total * 100)
            };
        }
    };

    console.log('[mc-web/chunks] Loader initialized with', MANIFEST.total, 'chunks');

    // Auto-preload first chunk immediately (contains runtime)
    if (typeof window.__webmcPreloadChunks !== 'boolean' || window.__webmcPreloadChunks) {
        setTimeout(() => {
            window.__webmcChunks.load(0).catch(e => {
                console.warn('[mc-web/chunks] Initial chunk preload failed, will load on demand');
            });
        }, 100);
    }

    // Preload remaining chunks after 5 seconds
    setTimeout(() => {
        window.__webmcChunks.preload(1, 10).catch(e => {});
    }, 5000);

})();